version: "3"

services: 
    challenge:
            container_name: flydevs-challenge
            restart: always
            build: .
            ports: 
                - "4040:3000"
            links: 
                - mongo
            volumes: 
                - .:/usr/src/app
    mongo:
        container_name: mongoDB
        image: mongo
        ports: 
            - "27017:27017"
        logging: 
            driver: none